const SET_MAIN_BUTTONS = 'SET_MAIN_BUTTONS[CONFIGS]';
const SET_MAIN_IMAGE_URLS = 'SET_MAIN_IMAGE_URLS[CONFIGS]';
const CHANGE_LANG = 'CHANGE_LANG[CONFIGS]';

export { SET_MAIN_BUTTONS, SET_MAIN_IMAGE_URLS, CHANGE_LANG };
