export const errors: { code: number; en: string; he: string }[] = [
  { code: 1, en: 'User not found', he: 'משתמש לא נמצא' },
  { code: 2, en: 'Object not found', he: 'אובייקט לא קיים' },
  { code: 4, en: 'Session key not exists', he: 'מזהה תהליך לא קיים' },
  { code: 7, en: 'User without permissions', he: 'למשתמש אין הרשאות' },
  { code: 8, en: 'Id is empty', he: 'ת.ז ריקה' },
  { code: 9, en: 'Duplicate Id', he: 'ת.ז כפולה' },
  { code: 20, en: 'Update error', he: 'שגיאת עדכון נתונים' },
  { code: 21, en: 'System error', he: 'שגיאת מערכת' },
  { code: 22, en: 'No permission', he: 'אין הרשאות לפעולה' },
  { code: 30, en: 'Empty name', he: 'שם פרטי ריק' },
  { code: 31, en: 'Duplicate name', he: 'שם שהוכנס כבר קיים במערכת' },
  { code: 39, en: 'Duplicate code', he: 'קוד שהוכנס כבר קיים במערכת' },
  { code: 41, en: 'Transaction phase error', he: 'עסקה בטולה או נסגרה' },
  { code: 45, en: 'Duplicate card number', he: 'כרטיס שהוכנס כבר קיים במערכת' },
  { code: 53, en: 'User name already exists', he: 'שם משתמש זהה כבר קיים במערכת' },
  { code: 54, en: 'Password already exists', he: 'סיסמא זהה כבר קיימת במערכת' },
  { code: 55, en: 'Member card not in range', he: 'מספר כרטסי לא בטווח המותר' },
  { code: 56, en: 'Member group not in range', he: 'מספר קבוצה לא בטווח המותר' },
  { code: 68, en: 'Card number was in use', he: 'מספר כרטיס שהוקלד היה בשימוש' },
  { code: 69, en: 'Empty email', he: 'לא הוקלד מייל' },
  { code: 70, en: 'Error email', he: 'מייל שהוקלד שגוי' },
  { code: 71, en: 'Empty branch', he: 'לא הוקלד מזהה סניף' },
  { code: 72, en: 'Empty group', he: 'לא הוקלד מזהה קבוצה' },
  { code: 73, en: 'Empty Phone', he: 'לא הוקלד מספר טלפון' },
  { code: 74, en: 'Invalid Id', he: 'ת.ז שגויה' },
  { code: 75, en: 'Empty Id', he: 'ת.ז ריקה' },
  { code: 78, en: 'Empty first name', he: 'לא הוקלד שם פרטי' },
  { code: 79, en: 'Empty last name', he: 'לא הוקלד שם משפחה' },
  { code: 80, en: 'Wrong phone number', he: 'מספר טלפון שהוקלד שגוי' },
  { code: 82, en: 'Empty Birthday', he: 'לא הוקלד תאריך יום הולדתv' },
  { code: 84, en: 'Error Birthday', he: 'תאריך יום הולדת שהוקלד שגוי' },
  { code: 85, en: 'Value already exists', he: 'הוקלד ערך שכבר קיים במערכת' },
  { code: 89, en: 'Value over allow limit ', he: 'ערך שהוקלד גבוהה ממותר' },
  { code: 91, en: 'Value over allow limit', he: 'ערך שהוקלד גבוהה ממותר' },
  { code: 94, en: 'Invalid input value', he: 'ערך שהוקלד שגוי' },
  { code: 100, en: 'Empty transaction number', he: 'לא הוקלד מספר עסקה' },
  { code: 105, en: 'Duplicate phone number', he: 'הוקדל מספר טלפון שקיים במערכת' },
  { code: 106, en: 'Duplicate email', he: 'הוקלד מייל שקיים במערכת' },
  { code: 109, en: 'Please call to credit company', he: 'נא להתקשר לחברת האשראי' },
  { code: 113, en: 'Operation seller require', he: 'נא לבחור מוכרן' },
  { code: 116, en: 'Employee Code Require', he: 'נא להכניס קוד עובד' },
  { code: 117, en: 'Employee Code not found', he: 'קוד עובד לא קיים' },
  { code: 118, en: 'Employee CellPhone Wrong Or Empty', he: 'טלפון של עובד שגוי' },
  { code: 137, en: 'Item is not for sale', he: 'פריט לא למכירה' },
  { code: 138, en: 'Coordination Required', he: 'נדרש תאום הזמנה' },
  { code: 139, en: 'Cash Over Limit', he: 'סה"כ מזומן גדול מהמותר' }
];
