export const routes = {
  signIn: '/signIn',
  dashboard: '/dashboard',
  dailyInstructionEditor: '/dailyInstructionEditor',
  salesReports: '/reports/salesReports',
  ordersReports: '/reports/ordersReports',
  targetReports: '/reports/targetReports',
  zReports: '/reports/zReports',
  ticketReports: '/reports/tickerReports',
  keyboardEditor: '/keyboardEditor/:id/edit',
  keyboardEditorNew: '/keyboardEditor/new',
  catalog: '/catalog',
  sellers: '/sellers',
  keyboardEditorDuplicate: '/keyboardEditor/:id/duplicate',
  keyboardList: '/keyboardList',
  paymentsEditor: '/paymentsEditor',
  efficiencyReport: '/efficiencyReport',
  couponReport: '/couponReport',
  timeReport: '/timeReport',
  activityReport: '/activityReport',
  subscribeReport: '/subscribeReport'
};
